services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"


keycloak:
  realm_name: "fairdi_nomad_test"

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    include:
      - voila
      - jupyter2
    options:
      jupyter2:
        short_description: A jupyter webapp container with voila opens notebook
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/rotekekse/test_nomad_distro_pv/jupyter:main
        path_prefix: lab/tree
        with_path: true 
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de
      voila:
        short_description: A jupyter webapp container with voila opens voila
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/rotekekse/test_nomad_distro_pv/jupyter:main
        path_prefix: voila/render
        with_path: true
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de
  
meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enabled: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
